config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
         resources :comments, only: [:index, :create]
        end
      end    
    end
  end
  # Defines the root path route ("/")
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

  resources :posts, only: [:new, :create, :destroy]
  resources :comments, only: [:destroy]

  post '/posts/:post_id/comments', to: 'comments#create', as: 'post_comments'
  post '/posts/:post_id/likes', to: 'likes#create', as: 'post_likes'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :show, Post
    can :index, Post

    return unless user.present?

    can :new, Post, author: user
    can :create, Post, author: user
    can :destroy, Post, author: user

    can :create, Comment, author: user
    can :destroy, Comment, author: user

    return unless user.role == 'admin'

    can :destroy, Post
    can :destroy, Comment
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_comments_counter
  after_destroy :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250, too_long: '250 charactors are allowed' }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_create :update_user_post_count
  after_destroy :update_user_post_count

  def update_user_post_count
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments_post(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def limit_sentence(content)
    words = content.split
    return content unless words.count > 30

    limited_words = words.take(30)
    "#{limited_words.join(' ')} . . ."
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    post = Post.find(params['post_id'])
    comments = post.comments
    render json: comments
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Post not found' }, status: :not_found
  end

  def create
    if current_user.nil?
      render json: { error: 'User not found' }, status: :not_found
      return
    end

    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(
      text: params['text'],
      author: current_user
    )

    if @comment.save
      render json: post, status: :created
    else
      render json: post.errors, status: :unprocessable_entity
    end
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    user = User.find(params['user_id'])
    posts = user.posts
    render json: posts
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Request not found' }, status: :not_found
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include DeviseWhitelist
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(current_user, @post), notice: 'Comment was successfully created.'
    else
      redirect_to user_post_path(current_user, @post), alert: 'Comment could not be saved.'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to(&:turbo_stream)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new
    @like.author = current_user

    if @like.save
      redirect_to user_post_path(current_user, @post), notice: 'You just liked this post'
    else
      redirect_to user_post_path(current_user, @post), alert: 'Something went wrong. Like was not saved.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.recent_comments_post(10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_path(current_user, @post), notice: 'Post was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = @post.author
    if @post.destroy
      redirect_to user_path(@user), notice: 'Post was deleted.'
    else
      redirect_to user_path(@user), alert: 'Error deleting the post.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar has-background-dark mb-2 p-3" role="navigation" aria-label="main navigation">
  <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
  </a>

  <div class="navbar-end">
    <%= link_to "Sign Out", destroy_user_session_path(@post), method: :delete, data: { "turbo-method": :delete }, class: "button is-small is-primary" %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render partial: 'layouts/header' %>
    </header>
    <div class="is-flex is-justify-content-center">
      <span class="subtitle has-text-success-dark"><%= notice %></span>
      <span class="subtitle has-text-danger-dark"><%= alert %></span>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1 class="title is-flex is-justify-content-center has-text-grey-darker">List of all posts</h1>

<div class="container" style="width: 45%;">

<div class="is-flex mt-4 mb-4">
  <figure class="image is-128x128">
    <img class="is-rounded" src="<%= @user.photo %>" alt="user photo">
  </figure>
  <div class="column ml-3 has-background-light radius-all">
    <p class="title is-5 has-text-grey">Name: <%= @user.name %></p>
    <span class="title is-6 has-text-success has-background-success-light p-1 is-pulled-right">Number of posts: <%= @user.posts_counter %></span>
  </div>
</div>

<div class=" container is-flex is-justify-content-end mb-4">
  <%= link_to "New Post", new_post_path, class: "button is-info" %>
</div>

<% @posts.each do |post| %>
  <div class="column has-background-light radius-top">
    <p class="mb-1 has-text-link"><%= post.title %></p>
    <%= post.limit_sentence(post.text) %>
    <div class="mt-1 is-flex is-justify-content-space-between is-align-items-center is-italic">
      <%= link_to "Show details", user_post_path(@user, post), class: "button is-link is-light is-rounded is-small is-outlined" %>
      <div class="has-text-link is-size-6">Comments : <%= post.comments_counter%>, Likes : <%= post.likes_counter%></div>
    </div>
  </div>

  
  <div class="column has-background-white mb-4 radius-buttom">
    <% post.recent_comments_post.each do |comment| %>
      <div class="is-italic"><strong><%= comment.author.name %></strong>  : <%= comment.text %></div>
    <% end %>
  </div> 
<%end%>

<div class="is-flex is-justify-content-center">
  <%= link_to "Pagination", user_posts_path(@user), class: "button is-info is-light is-outlined is-rounded my-3" %>
</div>
</div>

app/views/posts/new.html.erb
<h1 class="title is-flex is-justify-content-center has-text-grey-darker">Create a Post</h1>


<div class="container" style="width: 45%;">
  <%= form_with scope: :post, url: posts_path do |form| %>
    <% if @post.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% @post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :title, class: "label" %>
      <%= form.text_field :title, class: "input" %>
    </div>

     <div class="mb-3">
      <%= form.label :text, class: "label" %>
      <%= form.text_area :text , class: "textarea is-bordered" %>
    </div>

    <div>
      <%= form.submit class: "button is-info" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1 class="title is-flex is-justify-content-center has-text-grey-darker">Detailed posts for a user</h1>

<div class="container mt-3" style="width: 45%;">
  <div class="column has-background-light radius-top">
    <div class="mt-1 mb-2 is-flex is-justify-content-space-between is-align-items-center is-italic">
      <p class="has-text-link"><%= @post.title %> by <%= @post.author.name%></p>
      <div class="has-text-link is-size-6">Comments : <%= @post.comments_counter%>, Likes : <%= @post.likes_counter%></div>
    </div>
    <%= @post.text %>

    <%= form_with scope: :like, url: post_likes_path(@post) do |form| %>
      <%= form.submit "Like Post", class: "button is-small is-info is-light is-outlined is-rounded mt-1" %>
    <% end %>
  </div>

    <div class="column has-background-white mb-5 radius-buttom">
      <% @comments.each do |comment| %>
      <div class="is-flex is-justify-content-space-between">
        <span class="is-italic"><strong><%= comment.author.name %></strong>  : <%= comment.text %></span>
        <span>
        <% if can? :destroy, comment %>
          <%= link_to "", comment_path(comment.id), method: :delete, data: { "turbo-method": :delete }, class: "delete is-small" %>
        <% end %>
      </span>
      </div>
    <% end %>
    <% if can? :destroy, @post %>
     <%= link_to "Delete this Posts", post_path(@post), method: :delete, data: { "turbo-method": :delete }, class: "button is-small is-danger is-light is-rounded my-3" %>
    <% end %>
  </div>
  
  <%= form_with scope: :comment, url: post_comments_path(@post) do |form| %>
    <div class="mb-3">
      <%= form.text_area :text , placeholder: "Type your comment here ...", class: "textarea is-bordered" %>
    </div>
    <div>
      <%= form.submit class: "button is-info" %>
    </div>
  <% end %>
</div>

<div class="is-flex is-justify-content-center">
  <%= link_to "Back to all posts", user_posts_path(@post.author), class: "button is-info is-light is-outlined is-rounded my-3" %>
</div>

app/views/users/index.html.erb
<h1 class="title is-flex is-justify-content-center has-text-grey-darker">List of all users</h1>

<div class="container" style="width: 45%;">
  <% @users.each do |user| %>
      <div class="is-flex my-6 is-justify-content-center">
        <figure class="image is-128x128">
          <img class="is-rounded" src="<%= user.photo %>" alt="user photo">
        </figure>
        <div class="mx-3 column has-background-white radius-all">
          <p class="title is-5 has-text-grey">Name: <%= user.name %></p>
          <p class="title is-6 is-pulled-right has-text-success has-background-success-light p-1">Number of posts: <%= user.posts_counter %></p>
          <%= link_to "View profile", user_path(user), class: "button is-link is-light is-rounded is-small" %>
        </div>
      </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1 class="title is-flex is-justify-content-center has-text-grey-darker">All posts by a user</h1>

<div class="is-flex mt-6 mb-4 is-justify-content-center">
  <figure class="image is-128x128">
    <img class="is-rounded" src="<%= @user.photo %>" alt="user photo">
  </figure>
  <div class="mx-3 box is-shadowless has-background-light" style="width: 35%;">
    <p class="title is-5 has-text-grey">Name: <%= @user.name %></p>
    <p class="title is-6 is-pulled-right has-text-success has-background-success-light p-1">Number of posts: <%= @user.posts_counter %></p>
  </div>
</div>

<div class="container" style="width: 45%;">
  <div class="column has-background-light radius-top">
    <h2 class="has-text-link">Bio</h2>
    <%= @user.bio %>
  </div>

  <% @recent_posts.each do |post| %>
    <div class="column has-background-white mb-5 radius-buttom">
      <p class="mb-1 has-text-link"><%= post.title %></p>
      <%= post.limit_sentence(post.text) %>
      <div class="has-text-link is-flex is-justify-content-end is-italic">
      Comments : <%= post.comments_counter%>, Likes : <%= post.likes_counter%> 
      </div>
    </div>
  <%end%>

  <div class="is-flex is-justify-content-center mt-1">
    <%= link_to "See all posts", user_posts_path(@user), class: "button is-info is-light is-outlined is-rounded my-3" %>
  </div>
</div>